### ISSUE TITLE
dio htto cookie - exception ._rootRunUnary (.java) 

### ISSUE THREAD

**Issue by yyyy-ltd** [dart-tools/dio_http#11]
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
FileSystemException: Deletion failed, path = '/data/user/0/com.foryou.challenge/app_flutter/.cookies/ie0_ps1/' (OS Error: Invalid argument, errno = 22). Error thrown null.

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FileSystemException: Deletion failed, path = '/data/user/0/com.aaa.aaa/app_flutter/.cookies/ie0_ps1/' (OS Error: Invalid argument, errno = 22). Error thrown null.
       at ._rootRunUnary(.java)
       at FileStorage.deleteAll(FileStorage.java:30)
       at PersistCookieJar.deleteAll(PersistCookieJar.java:165)
       at AppHttpClient.fetchNewCookieCookie(AppHttpClient.java:73)
       at AppHttpClient.init(AppHttpClient.java:57)
       at .initApp(.java:30)
       at _FutureBuilderState._subscribe.<fn>(_subscribe.java:794)

**Comment by unacorbatanegra** [comment]
You have to provide more info in order to detect the issue

**Comment by jgoyvaerts** [comment]
This package is now archived. This was originally forked because the owner of the [Dio](https://github.com/flutterchina/dio) package was inactive, but he has sinced returned from inactiveness and has added some more contributors to prevent this from happening again in the future. All future development continues over on [Dio](https://github.com/flutterchina/dio).
