### ISSUE TITLE
[proposal] consider http/3 implementation based on cronet

### ISSUE THREAD

**Issue by iapicca** [dart-tools/dio_http#14]
please consider implementing http/3 with [cronet](https://github.com/google/cronet.dart)

- [ x ] I have searched for a similar issue in the [project](https://github.com/dart-tools/dio_http/issues) and found none

see also
https://github.com/grpc/grpc-dart/issues/374
https://github.com/google/cronet.dart/issues/5
https://github.com/fluttercommunity/community/issues/59

**Comment by jgoyvaerts** [comment]
This package is now archived. This was originally forked because the owner of the [Dio](https://github.com/flutterchina/dio) package was inactive, but he has sinced returned from inactiveness and has added some more contributors to prevent this from happening again in the future. All future development continues over on [Dio](https://github.com/flutterchina/dio).
