### ISSUE TITLE
ErrorInterceptorHandler(handler) doesn't work after unlocking dio

### ISSUE THREAD

**Issue by Okiring** [dart-tools/dio_http#2]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/dart-tools/dio_http/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                        |      |
| Platform Version               | 2.0.5                             |      |
| Dio Version                    | 5.0.4                                  |      |
| Android Studio / Xcode Version | 4.3.1             |      |
| Repro rate                     | all the time  |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

am using an interceptor and discovered something very odd during the usage. Am using the interceptor for refreshing the access token incase it expires. I only retry the request once and if that fails, am using the handler.next to complete the error..

![Screen Shot 2021-09-08 at 5 41 12 PM](https://user-images.githubusercontent.com/27002476/132549776-d7f9a649-31d4-4b5e-90cf-808a50929395.png)

when an error occurs without need to refresh the token ( lock , refresh the token and unlock the dio instance, then remake the previous request as shown in the pic), the handler.next function works fine and is able to pass back the error to my try-catch block...HOWEVER, when the access-token is refreshed and the previous request is re-made with the new acquired token, incase the request fails with an error e.g 4xx,5xx or any error, the onError is recalled and the handler.next function fires but the error is never caught by the try-catch block of my calling function
![Screen Shot 2021-09-08 at 5 22 19 PM](https://user-images.githubusercontent.com/27002476/132549630-99f27a0a-50de-44b2-9d0e-8de5e71437e1.png)
![Screen Shot 2021-09-08 at 5 23 24 PM](https://user-images.githubusercontent.com/27002476/132549666-3fc66291-d33a-4121-a9ad-3caa9f166ac4.png)

**Comment by miDeb** [comment]
It's difficult to tell what the issue is without seeing the whole code. In the future, please do not post screenshots of code, but instead create a minimal reproducible example, i.e. a small project that triggers the bug with as little code as possible.

Here's my guess of what's going wrong: You are returning the result of calling `networkDio.fetch(requestOperation)`. However, that's not the result of the network request, but a `Future`. Whoever then awaits the `Future` will see the error. Could you try changing `return networkDio.fetch(requestOperation)` to `return await networkDio.fetch(requestOperation)`?

I'm not sure I understood your issue correctly, so if the problem doesn't go away please improve your issue with a small demo project to trigger the bug so we can investigate better.

**Comment by Okiring** [comment]
thanks..actually your right..i wasn't waiting for the future when calling the fetch on the dio instance..working fine now..
